'''

Wir haben nun gesehen wie wir einen Fehler abfangen können. Allerdings 
gibt es Fälle wo gewisse Logik-Abschnitte mehrere Fehler auslösen können.

Lass uns einen Fall durchgehen!

'''


def main():
    pass


if __name__ == "__main__":
    main()